//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjGetShopee_v2._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.CommentPics = new HashSet<CommentPic>();
        }
    
        public int CommentID { get; set; }
        public int OrderDetailID { get; set; }
        public string Comment1 { get; set; }
        public byte CommentStar { get; set; }
        public System.DateTime CommentTime { get; set; }
        public int ShipperStar { get; set; }
        public string Comment2 { get; set; }
        public string Comment3 { get; set; }
    
        public virtual OrderDetail OrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentPic> CommentPics { get; set; }
    }
}
