//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjGetShopee_v2._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentToProduct
    {
        public int PaymentToProductID { get; set; }
        public int PaymentID { get; set; }
        public int ProductID { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual Product Product { get; set; }
    }
}
