//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjGetShopee_v2._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ADToProducts = new HashSet<ADToProduct>();
            this.Likes = new HashSet<Like>();
            this.PaymentToProducts = new HashSet<PaymentToProduct>();
            this.ProductDetails = new HashSet<ProductDetail>();
            this.ProductPics = new HashSet<ProductPic>();
            this.Reports = new HashSet<Report>();
            this.ShipperToProducts = new HashSet<ShipperToProduct>();
            this.SubOfficialEventToProducts = new HashSet<SubOfficialEventToProduct>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public int SmallTypeID { get; set; }
        public int MemberID { get; set; }
        public int RegionID { get; set; }
        public string Description { get; set; }
        public int ProductStatusID { get; set; }
        public System.DateTime EditTime { get; set; }
        public int CustomizedCategoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADToProduct> ADToProducts { get; set; }
        public virtual CustomizedCategory CustomizedCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Like> Likes { get; set; }
        public virtual MemberAccount MemberAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentToProduct> PaymentToProducts { get; set; }
        public virtual ProductStatu ProductStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDetail> ProductDetails { get; set; }
        public virtual SmallType SmallType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPic> ProductPics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
        public virtual RegionList RegionList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipperToProduct> ShipperToProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubOfficialEventToProduct> SubOfficialEventToProducts { get; set; }
    }
}
